Libary

In [302]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import accuracy_score
from sklearn.model_selection import cross_val_score
from sklearn.metrics import confusion_matrix
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import f1_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
from sklearn.metrics import r2_score

Dataset

In [303]:
data=pd.read_csv('global_fuel_prices_2020_2026.csv')
data

,date,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage
0,2020-01-06,United States,North America,High,Low,1.465,1.289,1.093,65.75,59.6
1,2020-01-13,United States,North America,High,Low,1.435,1.319,1.077,65.54,27.6
2,2020-01-20,United States,North America,High,Low,1.446,1.329,1.080,66.51,62.3
3,2020-01-27,United States,North America,High,Low,1.488,1.359,1.125,68.79,44.8
4,2020-02-03,United States,North America,High,Low,1.457,1.341,1.111,68.44,51.4
...,...,...,...,...,...,...,...,...,...,...
27463,2026-03-09,Rwanda,Africa,Low,Low,3.036,2.849,2.294,130.00,62.3
27464,2026-03-16,Rwanda,Africa,Low,Low,3.020,2.861,2.248,130.00,43.3
27465,2026-03-23,Rwanda,Africa,Low,Low,3.072,2.825,2.334,130.00,64.1
27466,2026-03-30,Rwanda,Africa,Low,Low,3.045,2.816,2.282,130.00,43.7
27467,2026-04-06,Rwanda,Africa,Low,Low,3.064,2.846,2.296,130.00,63.7

In [304]:
# convert date
data['date'] = pd.to_datetime(data['date'])

# extract
data['year'] = data['date'].dt.year
data['month'] = data['date'].dt.month

# drop original
data.drop('date', axis=1, inplace=True)

In [305]:
data.shape

(27468, 11)

Find Unique Value

In [306]:
for col in data.columns:
    print(col, ":", data[col].unique())

country : <StringArray>
[ 'United States',         'Canada',         'Mexico',         'Brazil',
      'Argentina',       'Colombia',          'Chile',           'Peru',
      'Venezuela',        'Ecuador', 'United Kingdom',        'Germany',
         'France',          'Italy',          'Spain',    'Netherlands',
        'Belgium',         'Sweden',         'Norway',        'Denmark',
        'Finland',         'Poland',       'Portugal',         'Greece',
    'Switzerland',        'Austria',        'Ireland',        'Hungary',
 'Czech Republic',        'Romania',         'Russia',        'Ukraine',
         'Turkey',          'China',          'Japan',    'South Korea',
          'India',      'Indonesia',       'Malaysia',       'Thailand',
        'Vietnam',    'Philippines',     'Bangladesh',       'Pakistan',
      'Sri Lanka',          'Nepal',        'Myanmar',      'Singapore',
      'Hong Kong',         'Taiwan',      'Australia',    'New Zealand',
   'Saudi Arabia',            'UAE',         'Kuwait',          'Qatar',
           'Iran',           'Iraq',         'Israel',         'Jordan',
        'Lebanon',          'Egypt',   'South Africa',        'Nigeria',
          'Kenya',       'Ethiopia',          'Ghana',       'Tanzania',
        'Morocco',        'Algeria',          'Libya',        'Tunisia',
         'Angola',     'Mozambique',         'Zambia',       'Zimbabwe',
         'Uganda',       'Cameroon',        'Senegal',    'Ivory Coast',
          'Sudan',       'Botswana',        'Namibia',         'Rwanda']
Length: 84, dtype: str
region : <StringArray>
['North America', 'South America',        'Europe',          'Asia',
       'Oceania',   'Middle East',        'Africa']
Length: 7, dtype: str
income_level : <StringArray>
['High', 'Middle', 'Low']
Length: 3, dtype: str
subsidy_level : <StringArray>
['Low', 'High', 'Medium', 'Very High']
Length: 4, dtype: str
petrol_usd_liter : [1.465 1.435 1.446 ... 0.345 0.349 2.275]
diesel_usd_liter : [1.289 1.319 1.329 ... 2.041 2.12  2.785]
lpg_usd_liter : [1.093 1.077 1.08  ... 0.282 1.79  2.012]
brent_crude_usd : [ 65.75  65.54  66.51  68.79  68.44  68.09  70.46  71.61  70.53  65.65
  61.32  59.47  57.74  56.01  53.79  50.69  47.97  49.05  50.77  51.55
  52.63  53.87  55.28  57.35  58.25  59.78  61.46  62.06  63.77  64.61
  65.24  67.64  70.07  72.19  73.3   73.99  75.86  77.24  77.99  79.48
  80.04  82.36  83.38  85.21  86.33  87.87  89.46  90.33  92.77  94.82
  97.2   99.49 100.68 101.18 101.34 101.28  99.81  99.24  98.99 100.56
 101.27  99.46 100.15  99.98  99.47 100.5  102.04 103.46 102.75 102.68
 103.38 104.85 104.57 104.65 103.62 102.49 103.76 105.69 105.91 107.41
 108.14 107.67 108.4  110.55 110.81 112.98 110.14 111.43 111.83 111.77
 112.18 110.1  110.13 110.86 112.93 112.61 111.94 111.64 113.04 113.73
 113.4  114.31 114.73 116.19 115.65 115.56 115.39 113.93 114.59 115.61
 118.14 120.39 122.06 123.42 125.43 129.26 130.   129.44 128.03 126.78
 126.2  125.28 122.56 121.84 120.61 118.63 117.77 116.26 114.62 113.76
 112.17 111.12 109.67 108.22 106.91 106.28 104.52 103.54 102.76 102.2
 100.82  99.3   98.77  97.51  96.67  95.2   95.59  96.4   95.02  95.95
  95.71  95.13  93.8   93.27  94.1   95.67  96.46  98.5  102.31 101.82
 101.52  99.36 101.14 103.09 101.79 102.72 104.54 104.88 106.15 106.41
 104.59 106.16 108.15 109.25 107.82 106.69 105.   108.06 108.69 108.8
 109.02 106.97 105.81 107.13 106.77 108.58 109.39 113.49 113.63 111.52
 111.47 110.02 111.49 111.55 111.35 111.16 112.27 111.59 112.76 114.33
 113.81 112.42 111.66 112.72 112.86 113.8  116.45 116.8  115.58 117.17
 117.24 118.55 120.15 118.71 120.79 122.15 121.24 121.7  121.8  121.63
 122.48 124.   123.81 125.21 126.27 126.29 124.7  122.7  121.47 121.23
 120.38 118.04 118.27 117.57 117.47 115.59 117.26 117.22 117.68 115.95
 118.62 120.63 122.07 122.86 122.68 123.01 124.07 123.11 122.38 120.18
 119.05 120.85 120.24 119.66 119.84 117.71 118.64 119.96 120.22 122.
 120.21 122.22 121.14 119.41 118.92 120.97 120.74 119.42 117.67 117.34
 114.75 112.99 114.64 116.03 115.68 114.92 114.79 117.41 117.69 118.58
 118.01 118.59 118.54 116.06 117.4  116.46 118.8  119.31 119.63 119.3
 118.52 118.57 119.43 118.67 117.73 117.1  119.58 119.82 120.32 119.36
 120.67 119.62 124.85]
tax_percentage : [59.6 27.6 62.3 44.8 51.4 15.  58.8 17.9 55.2 14.7 14.6 33.3 16.5 51.
 57.8 14.1 48.3 42.1 20.3 18.9 61.3 30.9 32.8 65.  52.3 46.9 16.2 56.9
 58.2 21.7 31.6 53.1 57.4 63.9 29.  46.7 14.9 21.3 54.  58.  21.5 44.
 59.2 15.9 30.8 16.6 37.4 42.3 30.  29.6 18.4 64.  63.3 46.8 41.4 33.4
 16.3 36.5 28.5 42.8 29.2 56.3 21.1 38.8 26.6 22.8 44.3 17.7 53.4 23.7
 53.9 45.3 23.8 32.  43.4 61.4 31.9 54.2 29.1 22.4 33.  41.9 64.8 13.7
 20.5 41.1 40.8 32.5 11.5 19.8 15.5 31.8 26.1 62.2 11.2 25.  25.1 10.6
 43.  31.1 19.1 31.4 49.5 61.5 11.7 33.9 20.2 46.2 11.9 60.8 55.6 22.7
 27.3 27.5 11.3 61.6 44.5 33.2 25.8 12.3 62.  38.2 22.1 39.5 40.3 30.5
 56.8 24.7 57.7 48.4 58.4 28.4 37.9 44.7 63.  57.9 51.7 34.5 19.  33.1
 22.6 57.5 52.7 51.9 21.  26.  52.9 64.3 29.3 41.2 15.8 54.1 14.4 45.4
 14.5 30.4 34.1 42.6 50.3 37.1 31.5 52.5 43.9 36.1 42.2 13.1 12.2 35.
 11.6 19.7 21.9 32.2 54.4 27.9 34.7 22.5 35.5 38.5 61.  36.7 39.7 49.4
 47.5 49.  56.2 19.2 35.6 51.6 38.7 55.4 12.  37.3 43.3 18.1 11.4 37.8
 45.2 13.4 13.2 15.6 38.  30.2 11.1 21.8 16.  30.7 62.5 47.8 45.  50.6
 26.3 46.4 52.  44.4 52.6 46.1 43.7 56.6 51.5 64.2 23.6 40.5 58.7 10.2
 53.7 13.6 38.4 28.1 50.5 20.1 24.3 17.3 50.1 43.6 13.8 24.4 51.8 32.6
 12.9 50.2 63.5 40.9 57.3 40.  24.2 34.8 39.6 18.7 59.8 43.8 63.2 59.
 35.3 19.6 51.2 29.4 16.9 47.7 26.8 46.6 57.6 63.7 57.2 15.3 26.5 59.1
 64.7 13.5 43.1 36.8 24.  20.8 21.4 41.5 61.2 35.1 13.9 61.8 17.8 26.2
 48.1 30.6 28.7 59.5 43.2 18.5 20.7 24.9 36.9 36.2 42.4 31.3 41.8 62.6
 57.  38.1 17.4 10.8 50.7 52.1 54.5 37.5 12.8 25.5 27.7 16.8 23.3 38.6
 13.  10.  27.4 27.2 26.4 29.8 33.8 49.2 10.5 10.1 35.2 47.1 60.5 47.4
 12.7 14.  59.9 53.3 23.2 42.5 54.6 46.  26.7 50.8 39.9 49.3 38.3 35.4
 50.  54.9 17.2 53.8 51.3 19.9 14.2 62.1 49.8 55.3 45.7 34.4 58.5 16.1
 40.4 56.1 34.2 48.2 29.5 22.9 32.9 19.4 16.4 53.6 47.9 56.  53.5 30.3
 36.6 60.  12.1 21.6 47.3 48.  48.8 60.7 58.6 24.1 28.8 25.9 25.2 14.8
 19.3  8.4 24.8  4.3 11.   5.3  6.5 18.8  1.2  7.1  4.6  0.7  7.  20.4
 28.9 29.7  7.8  7.4  5.7  9.   4.9 22.  24.6  9.8 22.2 10.4  6.8  2.5
 28.   3.5 15.1 28.2  5.1  0.5  0.9 27.1  1.5 13.3  5.8  7.2  2.4  8.7
  6.   7.6  9.7 23.1 27.   4.   3.1  0.   2.6 18.2  2.9  3.8  1.7 26.9
 23.  17.5 15.2 29.9 28.6 11.8  6.3  8.9 23.5 17.1 20.   2.1  1.4  2.3
  3.   5.4  4.8 17.  18.   8.6  5.2  5.9  9.2  8.5  0.4  6.6  9.4  3.3
  9.9  4.1  1.6  5.   3.2  7.5 10.3 12.6  9.6 18.6  1.1  9.3  4.7  1.3
  4.4 22.3 25.4 14.3 24.5  5.5  3.6 25.3  9.5  6.1  1.   1.8  0.2 23.9
 16.7  9.1  0.8 27.8  7.3  8.8  8.2  8.3 10.7  2.7  5.6  6.2 23.4 12.5
  0.6  3.9  7.7  1.9  3.7  4.5 15.7 19.5 12.4 25.7  3.4  8.1  8.   6.4
  2.  20.9 28.3  2.2  6.9  7.9  0.3 10.9 21.2 25.6  0.1 17.6 20.6 18.3
 15.4 39.8 45.5 53.2 52.8 37.2 64.5 37.7 56.7 60.1 54.7 39.3 36.  37.
 55.  60.2 44.1 59.7 34.3 55.9 44.2 49.9 48.9 63.8 37.6 31.7 39.4 39.1
 43.5 61.1 41.3 33.5 45.6 55.8 58.9 41.6 35.9 42.7 48.6 34.6 36.4 62.8
 48.7 35.8 64.4 55.1 52.2 56.4 60.4 32.1 32.7 62.4 59.3 40.2  4.2  2.8
 33.7 53.  44.6 56.5 44.9 63.4 54.3 40.1 49.6 34.  49.7 38.9 54.8 47.6
 48.5 39.  50.4 55.5 63.1 59.4 58.1 45.1 58.3 64.6 40.6 47.2 62.7 60.6
 33.6 52.4 55.7 60.3 64.1 60.9 46.3 57.1 42.9 49.1 61.7 32.3 47.  45.9
 31.2 46.5 41.7 40.7 42.  31.  35.7 45.8 61.9 36.3 50.9 64.9 62.9 39.2
 51.1 32.4 30.1 34.9 63.6 41.   6.7]
year : [2020 2021 2022 2023 2024 2025 2026]
month : [ 1  2  3  4  5  6  7  8  9 10 11 12]

Count data in every coloum

In [307]:
data.count()

country             27468
region              27468
income_level        27468
subsidy_level       27468
petrol_usd_liter    27468
diesel_usd_liter    27468
lpg_usd_liter       27468
brent_crude_usd     27468
tax_percentage      27468
year                27468
month               27468
dtype: int64

Find Null Value

In [308]:
data.isnull().sum()

country             0
region              0
income_level        0
subsidy_level       0
petrol_usd_liter    0
diesel_usd_liter    0
lpg_usd_liter       0
brent_crude_usd     0
tax_percentage      0
year                0
month               0
dtype: int64

In [309]:
data.info()

<class 'pandas.DataFrame'>
RangeIndex: 27468 entries, 0 to 27467
Data columns (total 11 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   country           27468 non-null  str
 1   region            27468 non-null  str
 2   income_level      27468 non-null  str
 3   subsidy_level     27468 non-null  str
 4   petrol_usd_liter  27468 non-null  float64
 5   diesel_usd_liter  27468 non-null  float64
 6   lpg_usd_liter     27468 non-null  float64
 7   brent_crude_usd   27468 non-null  float64
 8   tax_percentage    27468 non-null  float64
 9   year              27468 non-null  int32
 10  month             27468 non-null  int32
dtypes: float64(5), int32(2), str(4)
memory usage: 2.1 MB

Data Prerocessing

In [310]:
le = LabelEncoder()

for col in ['country','region','income_level','subsidy_level']:
    data[col] = le.fit_transform(data[col])
data

,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage,year,month
0,79,4,0,1,1.465,1.289,1.093,65.75,59.6,2020,1
1,79,4,0,1,1.435,1.319,1.077,65.54,27.6,2020,1
2,79,4,0,1,1.446,1.329,1.080,66.51,62.3,2020,1
3,79,4,0,1,1.488,1.359,1.125,68.79,44.8,2020,1
4,79,4,0,1,1.457,1.341,1.111,68.44,51.4,2020,2
...,...,...,...,...,...,...,...,...,...,...,...
27463,59,0,1,1,3.036,2.849,2.294,130.00,62.3,2026,3
27464,59,0,1,1,3.020,2.861,2.248,130.00,43.3,2026,3
27465,59,0,1,1,3.072,2.825,2.334,130.00,64.1,2026,3
27466,59,0,1,1,3.045,2.816,2.282,130.00,43.7,2026,3
27467,59,0,1,1,3.064,2.846,2.296,130.00,63.7,2026,4

Split Data

In [311]:
#x = data.drop("petrol_usd_liter", axis=1)
x = data.drop(["petrol_usd_liter", "diesel_usd_liter","lpg_usd_liter"], axis=1)
#x = data['diesel_usd_liter']
y= data['petrol_usd_liter']
#x = x.values.reshape(-1,1)
print(x.shape)
print(y.shape)

(27468, 8)
(27468,)

In [312]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.2,random_state=42)

Regression Model Train

In [313]:
from sklearn.linear_model import LinearRegression
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR
from sklearn.neighbors import KNeighborsRegressor

In [314]:
models = {
    "Linear Regression": LinearRegression(),
    "Decision Tree Regression": DecisionTreeRegressor(),
    "Random Forest Regression": RandomForestRegressor(),
    "Support Vector Regression": SVR(),
    "K Nearest Neighbors Regression": KNeighborsRegressor()
}

In [315]:
for name, model in models.items():
    model.fit(x_train, y_train)
    y_pred = model.predict(x_test)

    r2 = r2_score(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    mae = mean_absolute_error(y_test, y_pred)

    print("Model:", name)
    print("R2 Score:", r2)
    print("MSE:", mse)
    print("RMSE:", rmse)
    print("MAE:", mae)
    print("Train:", model.score(x_train, y_train))
    print("Test:", model.score(x_test, y_test))
    print('\n')
    print("------------------------------------------------------\n")

Model: Linear Regression
R2 Score: 0.5282653334811989
MSE: 1.1103843117158012
RMSE: 1.053747745770211
MAE: 0.8691865118164188
Train: 0.5522820893877882
Test: 0.5282653334811989


------------------------------------------------------

Model: Decision Tree Regression
R2 Score: 0.9958992551707535
MSE: 0.009652465777737327
RMSE: 0.09824696319855045
MAE: 0.04590010921998725
Train: 1.0
Test: 0.9958992551707535


------------------------------------------------------

Model: Random Forest Regression
R2 Score: 0.9969841384980125
MSE: 0.0070988323220487915
RMSE: 0.08425456855297991
MAE: 0.042440573860016394
Train: 0.999627940256568
Test: 0.9969841384980125


------------------------------------------------------

Model: Support Vector Regression
R2 Score: 0.21347705104166925
MSE: 1.8513431496834267
RMSE: 1.3606407129302822
MAE: 1.0837809868365924
Train: 0.2099428316093841
Test: 0.21347705104166925


------------------------------------------------------

Model: K Nearest Neighbors Regression
R2 Score: 0.5610879411537563
MSE: 1.03312539644853
RMSE: 1.016427762533339
MAE: 0.7621129607718212
Train: 0.7266793257662927
Test: 0.5610879411537563


------------------------------------------------------

In [316]:
print(data.corr()["petrol_usd_liter"].sort_values(ascending=False))

petrol_usd_liter    1.000000
lpg_usd_liter       0.999917
diesel_usd_liter    0.999045
tax_percentage      0.522155
brent_crude_usd     0.263530
year                0.184963
region              0.042099
month               0.017594
country            -0.011574
subsidy_level      -0.315061
income_level       -0.548275
Name: petrol_usd_liter, dtype: float64

Classification Model Training

Label Encoding

In [317]:
le = LabelEncoder()

for col in ['country','region','income_level','subsidy_level']:
    data[col] = le.fit_transform(data[col])
data

,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage,year,month
0,79,4,0,1,1.465,1.289,1.093,65.75,59.6,2020,1
1,79,4,0,1,1.435,1.319,1.077,65.54,27.6,2020,1
2,79,4,0,1,1.446,1.329,1.080,66.51,62.3,2020,1
3,79,4,0,1,1.488,1.359,1.125,68.79,44.8,2020,1
4,79,4,0,1,1.457,1.341,1.111,68.44,51.4,2020,2
...,...,...,...,...,...,...,...,...,...,...,...
27463,59,0,1,1,3.036,2.849,2.294,130.00,62.3,2026,3
27464,59,0,1,1,3.020,2.861,2.248,130.00,43.3,2026,3
27465,59,0,1,1,3.072,2.825,2.334,130.00,64.1,2026,3
27466,59,0,1,1,3.045,2.816,2.282,130.00,43.7,2026,3
27467,59,0,1,1,3.064,2.846,2.296,130.00,63.7,2026,4

Feature Extraction

In [318]:
x_new=data.drop('income_level',axis=1)
y_new=data['income_level']

StandardScale

In [319]:
scale=StandardScaler()
x_new=scale.fit_transform(x_new)

In [320]:
data.corr()["income_level"].sort_values(ascending=False)

income_level        1.000000e+00
subsidy_level       9.652457e-02
year                4.114097e-13
brent_crude_usd     8.106669e-15
month              -1.425741e-15
country            -4.324945e-03
region             -5.987547e-02
tax_percentage     -3.400340e-01
petrol_usd_liter   -5.482754e-01
lpg_usd_liter      -5.483318e-01
diesel_usd_liter   -5.546607e-01
Name: income_level, dtype: float64

Check “Copying”

In [321]:
data.corr()

,country,region,income_level,subsidy_level,petrol_usd_liter,diesel_usd_liter,lpg_usd_liter,brent_crude_usd,tax_percentage,year,month
country,1.000000e+00,-1.844587e-01,-4.324945e-03,-5.888582e-02,-0.011574,-0.017104,-0.011356,4.546747e-15,0.060722,2.278856e-13,-7.153318e-16
region,-1.844587e-01,1.000000e+00,-5.987547e-02,1.055311e-02,0.042099,0.042666,0.042178,-2.092046e-14,-0.043108,-9.757675e-13,2.799321e-15
income_level,-4.324945e-03,-5.987547e-02,1.000000e+00,9.652457e-02,-0.548275,-0.554661,-0.548332,8.106669e-15,-0.340034,4.114097e-13,-1.425741e-15
subsidy_level,-5.888582e-02,1.055311e-02,9.652457e-02,1.000000e+00,-0.315061,-0.314924,-0.314827,8.014381e-15,-0.251448,2.588488e-13,-1.305238e-15
petrol_usd_liter,-1.157396e-02,4.209863e-02,-5.482754e-01,-3.150612e-01,1.000000,0.999045,0.999917,2.635300e-01,0.522155,1.849629e-01,1.759429e-02
diesel_usd_liter,-1.710418e-02,4.266642e-02,-5.546607e-01,-3.149238e-01,0.999045,1.000000,0.998964,2.588479e-01,0.522029,1.817064e-01,1.728090e-02
lpg_usd_liter,-1.135617e-02,4.217828e-02,-5.483318e-01,-3.148274e-01,0.999917,0.998964,1.000000,2.634895e-01,0.522152,1.849091e-01,1.758256e-02
brent_crude_usd,4.546747e-15,-2.092046e-14,8.106669e-15,8.014381e-15,0.263530,0.258848,0.263490,1.000000e+00,0.000568,7.017541e-01,6.707001e-02
tax_percentage,6.072176e-02,-4.310753e-02,-3.400340e-01,-2.514480e-01,0.522155,0.522029,0.522152,5.682524e-04,1.000000,-3.427018e-04,2.479250e-03
year,2.278856e-13,-9.757675e-13,4.114097e-13,2.588488e-13,0.184963,0.181706,0.184909,7.017541e-01,-0.000343,1.000000e+00,-9.540525e-02
month,-7.153318e-16,2.799321e-15,-1.425741e-15,-1.305238e-15,0.017594,0.017281,0.017583,6.707001e-02,0.002479,-9.540525e-02,1.000000e+00

In [322]:
x_new_test,x_new_train,y_new_test,y_new_train=train_test_split(x_new,y_new,test_size=0.2,random_state=42)

Model Training

In [323]:
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import classification_report

In [324]:
modelss = {
    "Logistic Regression": LogisticRegression(),
    "Decision Tree Classification": DecisionTreeClassifier(),
    "Random Forest Classification": RandomForestClassifier(n_estimators=200, max_depth=10),
    "Support Vector Classification": SVC(),
    "K Nearest Neighbors Classification": KNeighborsClassifier(),
    "Naive Bayes Classification": GaussianNB()
}

In [ ]:
for name, model in modelss.items():
    model.fit(x_new_train, y_new_train)
    y_new_pred = model.predict(x_new_test)
    ac = accuracy_score(y_new_test, y_new_pred)
    cm = confusion_matrix(y_new_test, y_new_pred)
    cr = classification_report(y_new_test, y_new_pred)

    print("Model:", name)
    print("Accuracy:", ac)
    print("Train:", model.score(x_new_train, y_new_train))
    print("Test:", model.score(x_new_test, y_new_test))
    print("\nConfusion Matrix:\n", cm)
    print("\nClassification Report:\n", cr)

    train_score = model.score(x_new_train, y_new_train)
    test_score = model.score(x_new_test, y_new_test)
        #overfitting checking
    if train_score - test_score > 0.1:
        print("Overfitting detected")
    else:
        print("No strong overfitting")

    #Shuffle Test
    y_new_test_shuffled = np.random.permutation(y_new_test)
    shuffled_score = model.score(x_new_test, y_new_test_shuffled)

    print("\nOriginal Score:", test_score)
    print("Shuffled Score:", shuffled_score)

    if abs(test_score - shuffled_score) < 0.05:
        print("Possible Data Leakage / Copying")
    else:
        print("Model is learning real patterns")

    #Cross Validation (BEST CHECK)
    cv_scores = cross_val_score(model, x_new_train, y_new_train, cv=5)

    print("\nCross Validation Scores:", cv_scores)
    print("CV Mean:", cv_scores.mean())

    if cv_scores.mean() < 0.7:
        print("Weak model")
    else:
        print("Stable model")

    print("\n" + "-"*60 + "\n")

Model: Logistic Regression
Accuracy: 0.7362792391007554
Train: 0.7520931925737168
Test: 0.7362792391007554

Confusion Matrix:
 [[7134   11 1197]
 [  25 4829 1139]
 [1427 1996 4216]]

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.86      0.84      8342
           1       0.71      0.81      0.75      5993
           2       0.64      0.55      0.59      7639

    accuracy                           0.74     21974
   macro avg       0.73      0.74      0.73     21974
weighted avg       0.73      0.74      0.73     21974

No strong overfitting

Original Score: 0.7362792391007554
Shuffled Score: 0.334941294256849
Model is learning real patterns

Cross Validation Scores: [0.74522293 0.75705187 0.76160146 0.73248408 0.73952641]
CV Mean: 0.7471773478456155
Stable model

------------------------------------------------------------

Model: Decision Tree Classification
Accuracy: 0.9960407754619095
Train: 1.0
Test: 0.9960407754619095

Confusion Matrix:
 [[8286    0   56]
 [   0 5993    0]
 [  18   13 7608]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      0.99      1.00      8342
           1       1.00      1.00      1.00      5993
           2       0.99      1.00      0.99      7639

    accuracy                           1.00     21974
   macro avg       1.00      1.00      1.00     21974
weighted avg       1.00      1.00      1.00     21974

No strong overfitting

Original Score: 0.9960407754619095
Shuffled Score: 0.334941294256849
Model is learning real patterns

Cross Validation Scores: [0.99272066 0.99272066 0.99454049 0.99363057 0.99180328]
CV Mean: 0.9930831307149569
Stable model

------------------------------------------------------------

Model: Random Forest Classification
Accuracy: 0.9811595521980523
Train: 0.9938114306516199
Test: 0.9811595521980523

Confusion Matrix:
 [[8313    0   29]
 [   0 5992    1]
 [  26  358 7255]]

Classification Report:
               precision    recall  f1-score   support

           0       1.00      1.00      1.00      8342
           1       0.94      1.00      0.97      5993
           2       1.00      0.95      0.97      7639

    accuracy                           0.98     21974
   macro avg       0.98      0.98      0.98     21974
weighted avg       0.98      0.98      0.98     21974

No strong overfitting

Original Score: 0.9811595521980523
Shuffled Score: 0.33771730226631475
Model is learning real patterns

Cross Validation Scores: [0.97816197 0.97361237 0.98362147 0.98271156 0.98816029]
CV Mean: 0.98125353235513
Stable model

------------------------------------------------------------